package vistas.Admin;

import javax.swing.JOptionPane;
import modelo.medico;

public class vtnAdminMedico extends javax.swing.JFrame {

    vtnAdmin ventAdmin = null;
    medico med = null;
    pnlAgregarMedico panAgregarMedico = new pnlAgregarMedico();
    pnlEditarMedico panEditarMedico = new pnlEditarMedico();
    pnlEliminarMedico panEliminarMedico = new pnlEliminarMedico();

    public vtnAdminMedico() {
        initComponents();
    }

    public vtnAdminMedico(vtnAdmin ventAdmin, medico med) {
        initComponents();
        this.ventAdmin = ventAdmin;
        this.med = med;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAdminMedico = new javax.swing.JPanel();
        pnlLista = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstOpciones = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        pnlAccion = new javax.swing.JPanel();
        pnlBotones = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        pnlDatos = new javax.swing.JPanel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pnlAdminMedico.setLayout(new java.awt.BorderLayout());

        pnlLista.setPreferredSize(new java.awt.Dimension(130, 400));

        lstOpciones.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lstOpciones.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Agregar Medico", "Editar Medico", "Eliminar Medico" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstOpciones.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstOpcionesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstOpciones);

        jButton1.setText("jButton1");

        javax.swing.GroupLayout pnlListaLayout = new javax.swing.GroupLayout(pnlLista);
        pnlLista.setLayout(pnlListaLayout);
        pnlListaLayout.setHorizontalGroup(
            pnlListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButton1)
                .addContainerGap(33, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        pnlListaLayout.setVerticalGroup(
            pnlListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListaLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pnlAdminMedico.add(pnlLista, java.awt.BorderLayout.LINE_END);

        pnlAccion.setLayout(new java.awt.BorderLayout());

        pnlBotones.setPreferredSize(new java.awt.Dimension(278, 30));

        jButton2.setText("jButton2");

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBotonesLayout.createSequentialGroup()
                .addGap(0, 195, Short.MAX_VALUE)
                .addComponent(jButton2))
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addComponent(jButton2)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        pnlAccion.add(pnlBotones, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout pnlDatosLayout = new javax.swing.GroupLayout(pnlDatos);
        pnlDatos.setLayout(pnlDatosLayout);
        pnlDatosLayout.setHorizontalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );
        pnlDatosLayout.setVerticalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        pnlAccion.add(pnlDatos, java.awt.BorderLayout.CENTER);

        pnlAdminMedico.add(pnlAccion, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlAdminMedico, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        ventAdmin.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void lstOpcionesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstOpcionesValueChanged
        switch(lstOpciones.getSelectedIndex()){
            case 1:
                pnlAccion = panAgregarMedico;
                pnlAccion.setVisible(true);
                break;
            case 2:
                pnlAccion = panEditarMedico;
                pnlAccion.setVisible(true);
                break;
        }
    }//GEN-LAST:event_lstOpcionesValueChanged
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vtnAdminMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vtnAdminMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vtnAdminMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vtnAdminMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vtnAdminMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstOpciones;
    private javax.swing.JPanel pnlAccion;
    private javax.swing.JPanel pnlAdminMedico;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlLista;
    // End of variables declaration//GEN-END:variables
}
