package vistas.Admin;

import javax.swing.JOptionPane;
import modelo.usuario;
import dao.UsuarioImpDao;

public class vtnAdminUsuario extends javax.swing.JFrame {

    vtnAdmin ventAdmin = null;
    usuario usu = null;
    UsuarioImpDao bdUsuario = new UsuarioImpDao();

    public vtnAdminUsuario() {
        initComponents();
    }

    public vtnAdminUsuario(vtnAdmin ventAdmin, usuario usu) {
        initComponents();
        this.ventAdmin = ventAdmin;
        this.usu = usu;
        ocultarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpTipoUsuarioAgregar = new javax.swing.ButtonGroup();
        grpTipoUsuarioEditar = new javax.swing.ButtonGroup();
        tbpUsuarios = new javax.swing.JTabbedPane();
        pnlAgregarUsuario = new javax.swing.JPanel();
        pnlAgregarUsuario1 = new javax.swing.JPanel();
        lblAgregarUsuario = new javax.swing.JLabel();
        btnGuardarAgregar = new javax.swing.JButton();
        pnlDatos = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblContreasena = new javax.swing.JLabel();
        txtContrasenaAgregar = new javax.swing.JTextField();
        txtApellidosAgregar = new javax.swing.JTextField();
        txtCodigoAgregar = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        txtNombreAgregar = new javax.swing.JTextField();
        lblApellidos = new javax.swing.JLabel();
        lblNombreUsuario = new javax.swing.JLabel();
        jrbUsuarioAgregar = new javax.swing.JRadioButton();
        jrbAdministradorAgregar = new javax.swing.JRadioButton();
        txtNombreUsuarioAgregar = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lblTipoUsuario = new javax.swing.JLabel();
        txtEmailAgregar = new javax.swing.JTextField();
        btnRegresarAgregar = new javax.swing.JButton();
        pnlEditarUsuario = new javax.swing.JPanel();
        lblContreasena1 = new javax.swing.JLabel();
        lblTipoUsuario1 = new javax.swing.JLabel();
        txtEmailEditar = new javax.swing.JTextField();
        lblApellidos1 = new javax.swing.JLabel();
        lblNombre1 = new javax.swing.JLabel();
        jrbAdministradorEditar = new javax.swing.JRadioButton();
        lblCodigo1 = new javax.swing.JLabel();
        txtCodigoEditar = new javax.swing.JTextField();
        txtContrasenaEditar = new javax.swing.JTextField();
        txtApellidosEditar = new javax.swing.JTextField();
        lblNombreUsuario1 = new javax.swing.JLabel();
        jrbUsuarioEditar = new javax.swing.JRadioButton();
        txtNombreUsuarioEditar = new javax.swing.JTextField();
        lblEmail1 = new javax.swing.JLabel();
        lblAgregarUsuario1 = new javax.swing.JLabel();
        btnGuardarEditar = new javax.swing.JButton();
        txtNombreEditar = new javax.swing.JTextField();
        btnRegresarEditar = new javax.swing.JButton();
        lblInstruccionesEditar = new javax.swing.JLabel();
        txtUsuarioBuscarEditar = new javax.swing.JTextField();
        btnBuscarEditar = new javax.swing.JButton();
        pnlEliminarUsuario = new javax.swing.JPanel();
        pnlComponentes = new javax.swing.JPanel();
        lblEliminarUsuario = new javax.swing.JLabel();
        txtUsuarioBuscarEliminar = new javax.swing.JTextField();
        lblCodigo2 = new javax.swing.JLabel();
        btnBuscarEliminar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtInfoUsuario = new javax.swing.JTextArea();
        btnEliminarUsuario = new javax.swing.JButton();
        btnRegresarEliminar = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pnlAgregarUsuario1.setPreferredSize(new java.awt.Dimension(400, 410));

        lblAgregarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblAgregarUsuario.setText("Agregar un usuario");

        btnGuardarAgregar.setText("Guardar usuario");
        btnGuardarAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarAgregarActionPerformed(evt);
            }
        });

        lblNombre.setText("Nombre:");

        lblContreasena.setText("Contraseña:");

        lblCodigo.setText("Codigo:");

        lblApellidos.setText("Apellidos:");

        lblNombreUsuario.setText("Nombre de usuario:");

        grpTipoUsuarioAgregar.add(jrbUsuarioAgregar);
        jrbUsuarioAgregar.setText("Usuario");

        grpTipoUsuarioAgregar.add(jrbAdministradorAgregar);
        jrbAdministradorAgregar.setText("Administrador");

        lblEmail.setText("Email:");

        lblTipoUsuario.setText("Tipo de usuario:");

        javax.swing.GroupLayout pnlDatosLayout = new javax.swing.GroupLayout(pnlDatos);
        pnlDatos.setLayout(pnlDatosLayout);
        pnlDatosLayout.setHorizontalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTipoUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrbAdministradorAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrbUsuarioAgregar))
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDatosLayout.createSequentialGroup()
                                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblContreasena)
                                    .addComponent(lblNombre)
                                    .addComponent(lblApellidos)
                                    .addComponent(lblNombreUsuario))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtNombreAgregar, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtApellidosAgregar, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtContrasenaAgregar, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombreUsuarioAgregar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlDatosLayout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblEmail)
                                    .addComponent(lblCodigo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCodigoAgregar)
                                    .addComponent(txtEmailAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlDatosLayout.setVerticalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombreAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidos)
                    .addComponent(txtApellidosAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreUsuario)
                    .addComponent(txtNombreUsuarioAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContreasena)
                    .addComponent(txtContrasenaAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmailAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(txtCodigoAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbUsuarioAgregar)
                    .addComponent(jrbAdministradorAgregar)
                    .addComponent(lblTipoUsuario))
                .addContainerGap())
        );

        btnRegresarAgregar.setText("Regresar");
        btnRegresarAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAgregarUsuario1Layout = new javax.swing.GroupLayout(pnlAgregarUsuario1);
        pnlAgregarUsuario1.setLayout(pnlAgregarUsuario1Layout);
        pnlAgregarUsuario1Layout.setHorizontalGroup(
            pnlAgregarUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgregarUsuario1Layout.createSequentialGroup()
                .addGroup(pnlAgregarUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAgregarUsuario1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(lblAgregarUsuario))
                    .addGroup(pnlAgregarUsuario1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(pnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAgregarUsuario1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(btnRegresarAgregar)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardarAgregar)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        pnlAgregarUsuario1Layout.setVerticalGroup(
            pnlAgregarUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAgregarUsuario1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblAgregarUsuario)
                .addGap(38, 38, 38)
                .addComponent(pnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(pnlAgregarUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarAgregar)
                    .addComponent(btnRegresarAgregar))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlAgregarUsuarioLayout = new javax.swing.GroupLayout(pnlAgregarUsuario);
        pnlAgregarUsuario.setLayout(pnlAgregarUsuarioLayout);
        pnlAgregarUsuarioLayout.setHorizontalGroup(
            pnlAgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAgregarUsuario1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
        );
        pnlAgregarUsuarioLayout.setVerticalGroup(
            pnlAgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAgregarUsuario1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
        );

        tbpUsuarios.addTab("Agregar Usuario", pnlAgregarUsuario);

        lblContreasena1.setText("Contraseña:");

        lblTipoUsuario1.setText("Tipo de usuario:");

        lblApellidos1.setText("Apellidos:");

        lblNombre1.setText("Nombre:");

        grpTipoUsuarioEditar.add(jrbAdministradorEditar);
        jrbAdministradorEditar.setText("Administrador");

        lblCodigo1.setText("Codigo:");

        lblNombreUsuario1.setText("Nombre de usuario:");

        grpTipoUsuarioEditar.add(jrbUsuarioEditar);
        jrbUsuarioEditar.setText("Usuario");

        lblEmail1.setText("Email:");

        lblAgregarUsuario1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblAgregarUsuario1.setText("Editar un usuario");

        btnGuardarEditar.setText("Guardar usuario");
        btnGuardarEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarEditarActionPerformed(evt);
            }
        });

        btnRegresarEditar.setText("Regresar");
        btnRegresarEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarEditarActionPerformed(evt);
            }
        });

        lblInstruccionesEditar.setText("Inserte el usuario a editar:");

        btnBuscarEditar.setText("Buscar");
        btnBuscarEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEditarUsuarioLayout = new javax.swing.GroupLayout(pnlEditarUsuario);
        pnlEditarUsuario.setLayout(pnlEditarUsuarioLayout);
        pnlEditarUsuarioLayout.setHorizontalGroup(
            pnlEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditarUsuarioLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(pnlEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEditarUsuarioLayout.createSequentialGroup()
                        .addComponent(btnRegresarEditar)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardarEditar)
                        .addGap(108, 108, 108))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEditarUsuarioLayout.createSequentialGroup()
                        .addGroup(pnlEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlEditarUsuarioLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(pnlEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlEditarUsuarioLayout.createSequentialGroup()
                                        .addGroup(pnlEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblCodigo1)
                                            .addComponent(lblEmail1)
                                            .addComponent(lblContreasena1)
                                            .addComponent(lblNombreUsuario1)
                                            .addComponent(lblApellidos1)
                                            .addComponent(lblNombre1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pnlEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtApellidosEditar)
                                            .addComponent(txtNombreUsuarioEditar, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtEmailEditar, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCodigoEditar, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtContrasenaEditar, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNombreEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(pnlEditarUsuarioLayout.createSequentialGroup()
                                        .addComponent(lblTipoUsuario1)
                                        .addGap(7, 7, 7)
                                        .addComponent(jrbAdministradorEditar)
                                        .addGap(5, 5, 5)
                                        .addComponent(jrbUsuarioEditar))))
                            .addGroup(pnlEditarUsuarioLayout.createSequentialGroup()
                                .addGroup(pnlEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblAgregarUsuario1)
                                    .addGroup(pnlEditarUsuarioLayout.createSequentialGroup()
                                        .addComponent(lblInstruccionesEditar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtUsuarioBuscarEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarEditar)))
                        .addGap(39, 39, 39))))
        );
        pnlEditarUsuarioLayout.setVerticalGroup(
            pnlEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditarUsuarioLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblAgregarUsuario1)
                .addGap(12, 12, 12)
                .addGroup(pnlEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuarioBuscarEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarEditar)
                    .addComponent(lblInstruccionesEditar))
                .addGap(18, 18, 18)
                .addGroup(pnlEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre1)
                    .addComponent(txtNombreEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidos1)
                    .addComponent(txtApellidosEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreUsuario1)
                    .addComponent(txtNombreUsuarioEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContreasena1)
                    .addComponent(txtContrasenaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmail1)
                    .addComponent(txtEmailEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo1)
                    .addComponent(txtCodigoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbUsuarioEditar)
                    .addComponent(jrbAdministradorEditar)
                    .addComponent(lblTipoUsuario1))
                .addGap(44, 44, 44)
                .addGroup(pnlEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarEditar)
                    .addComponent(btnRegresarEditar))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        tbpUsuarios.addTab("Editar Usuario", pnlEditarUsuario);

        lblEliminarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblEliminarUsuario.setText("Eliminar usuario");

        txtUsuarioBuscarEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioBuscarEliminarActionPerformed(evt);
            }
        });

        lblCodigo2.setText("Codigo del usuario a eliminar");

        btnBuscarEliminar.setText("Buscar");
        btnBuscarEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEliminarActionPerformed(evt);
            }
        });

        txtInfoUsuario.setColumns(20);
        txtInfoUsuario.setRows(5);
        jScrollPane2.setViewportView(txtInfoUsuario);

        btnEliminarUsuario.setText("Eliminar usuario");
        btnEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarUsuarioActionPerformed(evt);
            }
        });

        btnRegresarEliminar.setText("Regresar");
        btnRegresarEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlComponentesLayout = new javax.swing.GroupLayout(pnlComponentes);
        pnlComponentes.setLayout(pnlComponentesLayout);
        pnlComponentesLayout.setHorizontalGroup(
            pnlComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComponentesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlComponentesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblEliminarUsuario)
                        .addGap(107, 107, 107))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlComponentesLayout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())))
            .addGroup(pnlComponentesLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblCodigo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsuarioBuscarEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarEliminar)
                .addGap(0, 30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlComponentesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegresarEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminarUsuario)
                .addGap(78, 78, 78))
        );
        pnlComponentesLayout.setVerticalGroup(
            pnlComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComponentesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblEliminarUsuario)
                .addGap(18, 18, 18)
                .addGroup(pnlComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuarioBuscarEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodigo2)
                    .addComponent(btnBuscarEliminar))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addGap(24, 24, 24)
                .addGroup(pnlComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarUsuario)
                    .addComponent(btnRegresarEliminar)))
        );

        pnlEliminarUsuario.add(pnlComponentes);

        tbpUsuarios.addTab("Eliminar Usuario", pnlEliminarUsuario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbpUsuarios)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tbpUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        ventAdmin.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void btnRegresarEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarEliminarActionPerformed
        btnRegresarAgregarActionPerformed(evt);
        txtUsuarioBuscarEliminar.setText("");
        txtInfoUsuario.setText("");
        ocultarComponentes();
    }//GEN-LAST:event_btnRegresarEliminarActionPerformed

    private void btnEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarUsuarioActionPerformed
        bdUsuario.abrirConexion();
        bdUsuario.eliminarUsuario(txtUsuarioBuscarEliminar.getText());
        bdUsuario.cerrarConexion();
        JOptionPane.showMessageDialog(this, "Usuario eliminado correctamente.");
        ventAdmin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEliminarUsuarioActionPerformed

    private void btnBuscarEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEliminarActionPerformed
        bdUsuario.abrirConexion();
        bdUsuario.consultarUsuario(txtUsuarioBuscarEliminar.getText());
        bdUsuario.cerrarConexion();
        if(usu != null){
            mostrarComponentes();
            txtInfoUsuario.setText(usu.mostrarInfo());
        }else{
            JOptionPane.showMessageDialog(this, "El usuario buscado no existe en el registro.");
            ocultarComponentes();
        }
    }//GEN-LAST:event_btnBuscarEliminarActionPerformed

    private void txtUsuarioBuscarEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioBuscarEliminarActionPerformed

    }//GEN-LAST:event_txtUsuarioBuscarEliminarActionPerformed

    private void btnBuscarEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEditarActionPerformed
        bdUsuario.abrirConexion();
        usu = bdUsuario.consultarUsuario(txtUsuarioBuscarEditar.getText());
        bdUsuario.cerrarConexion();
        mostrarDatosEditar();
    }//GEN-LAST:event_btnBuscarEditarActionPerformed

    private void btnRegresarEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarEditarActionPerformed
        btnRegresarAgregarActionPerformed(evt);
    }//GEN-LAST:event_btnRegresarEditarActionPerformed

    private void btnGuardarEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarEditarActionPerformed
        capturarDatosEditar();
        bdUsuario.abrirConexion();
        bdUsuario.actualizarUsuario(usu, txtUsuarioBuscarEditar.getText());
        bdUsuario.cerrarConexion();
        JOptionPane.showMessageDialog(this, "Usuario editado correctamente.");
    }//GEN-LAST:event_btnGuardarEditarActionPerformed

    private void btnRegresarAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarAgregarActionPerformed
        ventAdmin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarAgregarActionPerformed

    private void btnGuardarAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarAgregarActionPerformed
        capturarDatosAgregar();
        bdUsuario.abrirConexion();
        bdUsuario.agregarUsuario(usu);
        bdUsuario.cerrarConexion();
        JOptionPane.showMessageDialog(this, "Usuario agregado correctamente.");
    }//GEN-LAST:event_btnGuardarAgregarActionPerformed

    private void ocultarComponentes(){
        txtInfoUsuario.setVisible(false);
        btnEliminarUsuario.setVisible(false);
    }

    private void mostrarComponentes(){
        txtInfoUsuario.setVisible(true);
        btnEliminarUsuario.setVisible(true);
    }

    private void capturarDatosAgregar(){
        usu.setNombre(txtNombreAgregar.getText());
        usu.setApellido(txtApellidosAgregar.getText());
        usu.setNombreUsuario(txtNombreUsuarioAgregar.getText());
        usu.setContrasena(txtContrasenaAgregar.getText());
        usu.setEmail(txtEmailAgregar.getText());
        usu.setCodigo(txtCodigoAgregar.getText());
        if(jrbAdministradorAgregar.isSelected()){
            usu.setTipoUsuario("Administrador");
        }else{
            usu.setTipoUsuario("Usuario");
        }
    }
    
    private void capturarDatosEditar(){
        usu.setNombre(txtNombreEditar.getText());
        usu.setApellido(txtApellidosEditar.getText());
        usu.setNombreUsuario(txtNombreUsuarioEditar.getText());
        usu.setContrasena(txtContrasenaEditar.getText());
        usu.setEmail(txtEmailEditar.getText());
        usu.setCodigo(txtCodigoEditar.getText());
        if(jrbAdministradorEditar.isSelected()){
            usu.setTipoUsuario("Administrador");
        } else {
            usu.setTipoUsuario("Usuario");
        }
    }
    
    private void mostrarDatosEditar() {
        txtNombreEditar.setText(usu.getNombre());
        txtApellidosEditar.setText(usu.getApellido());
        txtEmailEditar.setText(usu.getEmail());
        txtCodigoEditar.setText(usu.getCodigo());
        txtNombreUsuarioEditar.setText(usu.getNombreUsuario());
        txtContrasenaEditar.setText(usu.getContrasena());
        if(usu.getTipoUsuario().equals("Administrador")){
            jrbAdministradorEditar.setSelected(true);
        }else{
            jrbUsuarioEditar.setSelected(true);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vtnAdminUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vtnAdminUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vtnAdminUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vtnAdminUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vtnAdminUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarEditar;
    private javax.swing.JButton btnBuscarEliminar;
    private javax.swing.JButton btnEliminarUsuario;
    private javax.swing.JButton btnGuardarAgregar;
    private javax.swing.JButton btnGuardarEditar;
    private javax.swing.JButton btnRegresarAgregar;
    private javax.swing.JButton btnRegresarEditar;
    private javax.swing.JButton btnRegresarEliminar;
    private javax.swing.ButtonGroup grpTipoUsuarioAgregar;
    private javax.swing.ButtonGroup grpTipoUsuarioEditar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton jrbAdministradorAgregar;
    private javax.swing.JRadioButton jrbAdministradorEditar;
    private javax.swing.JRadioButton jrbUsuarioAgregar;
    private javax.swing.JRadioButton jrbUsuarioEditar;
    private javax.swing.JLabel lblAgregarUsuario;
    private javax.swing.JLabel lblAgregarUsuario1;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblApellidos1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCodigo1;
    private javax.swing.JLabel lblCodigo2;
    private javax.swing.JLabel lblContreasena;
    private javax.swing.JLabel lblContreasena1;
    private javax.swing.JLabel lblEliminarUsuario;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmail1;
    private javax.swing.JLabel lblInstruccionesEditar;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JLabel lblNombreUsuario1;
    private javax.swing.JLabel lblTipoUsuario;
    private javax.swing.JLabel lblTipoUsuario1;
    private javax.swing.JPanel pnlAgregarUsuario;
    private javax.swing.JPanel pnlAgregarUsuario1;
    private javax.swing.JPanel pnlComponentes;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlEditarUsuario;
    private javax.swing.JPanel pnlEliminarUsuario;
    private javax.swing.JTabbedPane tbpUsuarios;
    private javax.swing.JTextField txtApellidosAgregar;
    private javax.swing.JTextField txtApellidosEditar;
    private javax.swing.JTextField txtCodigoAgregar;
    private javax.swing.JTextField txtCodigoEditar;
    private javax.swing.JTextField txtContrasenaAgregar;
    private javax.swing.JTextField txtContrasenaEditar;
    private javax.swing.JTextField txtEmailAgregar;
    private javax.swing.JTextField txtEmailEditar;
    private javax.swing.JTextArea txtInfoUsuario;
    private javax.swing.JTextField txtNombreAgregar;
    private javax.swing.JTextField txtNombreEditar;
    private javax.swing.JTextField txtNombreUsuarioAgregar;
    private javax.swing.JTextField txtNombreUsuarioEditar;
    private javax.swing.JTextField txtUsuarioBuscarEditar;
    private javax.swing.JTextField txtUsuarioBuscarEliminar;
    // End of variables declaration//GEN-END:variables
}
