package visual;

import java.awt.BorderLayout;
import java.util.ArrayList;

import javax.swing.JOptionPane;

public class TabPaciente extends javax.swing.JPanel {

    private ArrayList<Paciente> listaPacientes;

    public TabPaciente() {
        initComponents();
        listaPacientes = new ArrayList<>(); // Inicializa la lista de pacientes
        actualizarComboBoxPacientes();
        
        cBoxPacientes.addActionListener((e) -> {
            String seleccion = (String) cBoxPacientes.getSelectedItem();
            if (seleccion != null && seleccion.equals("Agregar un paciente")) {
                agregarNuevoPaciente();
            } else {
                // Aquí puedes implementar la lógica para realizar acciones con el paciente seleccionado
                // Por ejemplo, mostrar información del paciente en otra parte de la ventana
                // o abrir una ventana de edición para el paciente seleccionado.
            }
        });

        setLayout(new BorderLayout());
        add(cBoxPacientes, BorderLayout.NORTH);
    }

    private void actualizarComboBoxPacientes() {
        cBoxPacientes.removeAllItems();
        for (Paciente paciente : listaPacientes) {
            cBoxPacientes.addItem(paciente.getNombre() + " " + paciente.getApellido());
        }
        cBoxPacientes.addItem("Agregar un paciente...");
    }

    private void agregarNuevoPaciente() {
        String nombrePaciente = JOptionPane.showInputDialog("Ingrese el nombre del nuevo paciente:");
        if (nombrePaciente != null && !nombrePaciente.isEmpty()) {
            // Crea un nuevo paciente y agrégalo a la lista
            Paciente nuevoPaciente = new Paciente(nombrePaciente, "");
            listaPacientes.add(nuevoPaciente);
            actualizarComboBoxPacientes();
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSeleccionarPaciente = new javax.swing.JLabel();
        btnIr = new javax.swing.JButton();
        cBoxPacientes = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(400, 300));

        lblSeleccionarPaciente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSeleccionarPaciente.setText("Seleccione el paciente:");

        btnIr.setText("Ir");

        cBoxPacientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(cBoxPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addComponent(lblSeleccionarPaciente)
                .addGap(111, 111, 111))
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(btnIr)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblSeleccionarPaciente)
                .addGap(30, 30, 30)
                .addComponent(cBoxPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnIr)
                .addContainerGap(149, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIr;
    private javax.swing.JComboBox<String> cBoxPacientes;
    private javax.swing.JLabel lblSeleccionarPaciente;
    // End of variables declaration//GEN-END:variables
}
