package visual;

public class VentanaPacientes extends javax.swing.JFrame {

    VentanaListaPacientes ventListaPacientes = null;
    EditarDatos ventEditarDatos = null;

    Paciente Jorge = new Paciente("Jorge", "Gonzalez Castillo", 25, "jorgegc@gmail.com", "3345216548", "Hombre", "Colombiano", "Magdalena", "B+", "Polen y tinta", "Tetanos y Rabia", "Si");
    Paciente Pedro = new Paciente("Pedro", "Cabrera Lozano", 36, "pedro123456@gmail.com", "3357495456", "Otro", "Mexicano", "Oaxaca", "A-", "Ninguna", "COVID-19 e Influenza", "Si");
    Paciente Alma = new Paciente("Alma Delfina", "López Cuevas", 26, "almadelfina@gmail.com", "3312322234", "Mujer", "Mexicana", "Jalisco", "O+", "Polvo", "Todas", "No");
    Paciente Luis = new Paciente("Luis Enrique", "Vazquez Becerril", 25, "luisvb98@gmail.com", "3345214631", "Hombre", "Mexicano", "Jalisco", "B-", "Ninguna", "Todas", "No");

    public VentanaPacientes() {
        initComponents();
        LlenadoDeDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoSexoPaciente1 = new javax.swing.ButtonGroup();
        grupoSexoPaciente2 = new javax.swing.ButtonGroup();
        grupoSexoPaciente3 = new javax.swing.ButtonGroup();
        grupoSexoPaciente4 = new javax.swing.ButtonGroup();
        tbpnPacientes = new javax.swing.JTabbedPane();
        tabPaciente1 = new javax.swing.JPanel();
        lblNombrePaciente1 = new javax.swing.JLabel();
        txtNombrePaciente1 = new javax.swing.JTextField();
        lblApellidosPaciente1 = new javax.swing.JLabel();
        txtApellidosPaciente1 = new javax.swing.JTextField();
        lblEdadPaciente1 = new javax.swing.JLabel();
        txtEdadPaciente1 = new javax.swing.JTextField();
        lblEmailPaciente1 = new javax.swing.JLabel();
        txtEmailPaciente1 = new javax.swing.JTextField();
        lblTelefonoPaciente1 = new javax.swing.JLabel();
        txtTelefonoPaciente1 = new javax.swing.JTextField();
        lblSexoPaciente1 = new javax.swing.JLabel();
        rbHombrePaciente1 = new javax.swing.JRadioButton();
        rbMujerPaciente1 = new javax.swing.JRadioButton();
        rbOtroPaciente1 = new javax.swing.JRadioButton();
        lblNacionalidadPaciente1 = new javax.swing.JLabel();
        txtNacionalidadPaciente1 = new javax.swing.JTextField();
        lblResidenciaPaciente1 = new javax.swing.JLabel();
        txtResidenciaPaciente1 = new javax.swing.JTextField();
        lblTipoSangrePaciente1 = new javax.swing.JLabel();
        txtTipoSangrePaciente1 = new javax.swing.JTextField();
        lblAlergiasPaciente1 = new javax.swing.JLabel();
        txtAlergiasPaciente1 = new javax.swing.JTextField();
        lblVacunasPaciente1 = new javax.swing.JLabel();
        txtVacunasPaciente1 = new javax.swing.JTextField();
        lblPrioritarioPaciente1 = new javax.swing.JLabel();
        lblPrioritarioSiNoPaciente1 = new javax.swing.JLabel();
        btnEditarDatosPaciente1 = new javax.swing.JButton();
        btnCambiarVistaPaciente1 = new javax.swing.JButton();
        tabPaciente2 = new javax.swing.JPanel();
        lblNombrePaciente2 = new javax.swing.JLabel();
        txtNombrePaciente2 = new javax.swing.JTextField();
        lblApellidosPaciente2 = new javax.swing.JLabel();
        txtApellidosPaciente2 = new javax.swing.JTextField();
        lblEdadPaciente2 = new javax.swing.JLabel();
        txtEdadPaciente2 = new javax.swing.JTextField();
        lblEmailPaciente2 = new javax.swing.JLabel();
        txtEmailPaciente2 = new javax.swing.JTextField();
        lblTelefonoPaciente2 = new javax.swing.JLabel();
        txtTelefonoPaciente2 = new javax.swing.JTextField();
        lblSexoPaciente2 = new javax.swing.JLabel();
        rbHombrePaciente2 = new javax.swing.JRadioButton();
        rbMujerPaciente2 = new javax.swing.JRadioButton();
        rbOtroPaciente2 = new javax.swing.JRadioButton();
        lblNacionalidadPaciente2 = new javax.swing.JLabel();
        txtNacionalidadPaciente2 = new javax.swing.JTextField();
        lblResidenciaPaciente2 = new javax.swing.JLabel();
        txtResidenciaPaciente2 = new javax.swing.JTextField();
        lblTipoSangrePaciente2 = new javax.swing.JLabel();
        txtTipoSangrePaciente2 = new javax.swing.JTextField();
        lblAlergiasPaciente2 = new javax.swing.JLabel();
        txtAlergiasPaciente2 = new javax.swing.JTextField();
        lblVacunasPaciente2 = new javax.swing.JLabel();
        txtVacunasPaciente2 = new javax.swing.JTextField();
        lblPrioritarioPaciente2 = new javax.swing.JLabel();
        lblPrioritarioSiNoPaciente2 = new javax.swing.JLabel();
        btnEditarDatosPaciente2 = new javax.swing.JButton();
        btnCambiarVistaPaciente2 = new javax.swing.JButton();
        tabPaciente3 = new javax.swing.JPanel();
        lblNombrePaciente3 = new javax.swing.JLabel();
        txtNombrePaciente3 = new javax.swing.JTextField();
        lblApellidosPaciente3 = new javax.swing.JLabel();
        txtApellidosPaciente3 = new javax.swing.JTextField();
        lblEdadPaciente3 = new javax.swing.JLabel();
        txtEdadPaciente3 = new javax.swing.JTextField();
        lblEmailPaciente3 = new javax.swing.JLabel();
        txtEmailPaciente3 = new javax.swing.JTextField();
        lblTelefonoPaciente3 = new javax.swing.JLabel();
        txtTelefonoPaciente3 = new javax.swing.JTextField();
        lblSexoPaciente3 = new javax.swing.JLabel();
        rbHombrePaciente3 = new javax.swing.JRadioButton();
        rbMujerPaciente3 = new javax.swing.JRadioButton();
        rbOtroPaciente3 = new javax.swing.JRadioButton();
        lblNacionalidadPaciente3 = new javax.swing.JLabel();
        txtNacionalidadPaciente3 = new javax.swing.JTextField();
        lblResidenciaPaciente3 = new javax.swing.JLabel();
        txtResidenciaPaciente3 = new javax.swing.JTextField();
        lblTipoSangrePaciente3 = new javax.swing.JLabel();
        txtTipoSangrePaciente3 = new javax.swing.JTextField();
        lblAlergiasPaciente3 = new javax.swing.JLabel();
        txtAlergiasPaciente3 = new javax.swing.JTextField();
        lblVacunasPaciente3 = new javax.swing.JLabel();
        txtVacunasPaciente3 = new javax.swing.JTextField();
        lblPrioritarioSiNoPaciente3 = new javax.swing.JLabel();
        lblPrioritarioPaciente3 = new javax.swing.JLabel();
        btnEditarDatosPaciente3 = new javax.swing.JButton();
        btnCambiarVistaPaciente3 = new javax.swing.JButton();
        tabPaciente4 = new javax.swing.JPanel();
        lblNombrePaciente4 = new javax.swing.JLabel();
        txtNombrePaciente4 = new javax.swing.JTextField();
        lblApellidosPaciente4 = new javax.swing.JLabel();
        txtApellidosPaciente4 = new javax.swing.JTextField();
        lblEdadPaciente4 = new javax.swing.JLabel();
        txtEdadPaciente4 = new javax.swing.JTextField();
        lblEmailPaciente4 = new javax.swing.JLabel();
        txtEmailPaciente4 = new javax.swing.JTextField();
        lblTelefonoPaciente4 = new javax.swing.JLabel();
        txtTelefonoPaciente4 = new javax.swing.JTextField();
        lblSexoPaciente4 = new javax.swing.JLabel();
        rbHombrePaciente4 = new javax.swing.JRadioButton();
        rbMujerPaciente4 = new javax.swing.JRadioButton();
        rbOtroPaciente4 = new javax.swing.JRadioButton();
        lblNacionalidadPaciente4 = new javax.swing.JLabel();
        txtNacionalidadPaciente4 = new javax.swing.JTextField();
        lblResidenciaPaciente4 = new javax.swing.JLabel();
        txtResidenciaPaciente4 = new javax.swing.JTextField();
        lblTipoSangrePaciente4 = new javax.swing.JLabel();
        txtTipoSangrePaciente4 = new javax.swing.JTextField();
        lblAlergiasPaciente4 = new javax.swing.JLabel();
        txtAlergiasPaciente4 = new javax.swing.JTextField();
        lblVacunasPaciente4 = new javax.swing.JLabel();
        txtVacunasPaciente4 = new javax.swing.JTextField();
        lblPrioritarioPaciente4 = new javax.swing.JLabel();
        lblPrioritarioSiNoPaciente4 = new javax.swing.JLabel();
        btnEditarDatosPaciente4 = new javax.swing.JButton();
        btnCambiarVistaPaciente4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 550));

        tbpnPacientes.setPreferredSize(new java.awt.Dimension(400, 550));
        tbpnPacientes.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tbpnPacientesStateChanged(evt);
            }
        });

        tabPaciente1.setPreferredSize(new java.awt.Dimension(400, 550));

        lblNombrePaciente1.setText("Nombre:");

        txtNombrePaciente1.setEnabled(false);

        lblApellidosPaciente1.setText("Apellidos:");

        txtApellidosPaciente1.setEnabled(false);

        lblEdadPaciente1.setText("Edad:");

        txtEdadPaciente1.setEnabled(false);

        lblEmailPaciente1.setText("Email:");

        txtEmailPaciente1.setEnabled(false);

        lblTelefonoPaciente1.setText("Telefono:");

        txtTelefonoPaciente1.setEnabled(false);

        lblSexoPaciente1.setText("Sexo:");

        grupoSexoPaciente1.add(rbHombrePaciente1);
        rbHombrePaciente1.setText("Hombre");
        rbHombrePaciente1.setEnabled(false);

        grupoSexoPaciente1.add(rbMujerPaciente1);
        rbMujerPaciente1.setText("Mujer");
        rbMujerPaciente1.setEnabled(false);

        grupoSexoPaciente1.add(rbOtroPaciente1);
        rbOtroPaciente1.setText("Otro");
        rbOtroPaciente1.setEnabled(false);

        lblNacionalidadPaciente1.setText("Nacionalidad:");

        txtNacionalidadPaciente1.setEnabled(false);

        lblResidenciaPaciente1.setText("Residencia:");

        txtResidenciaPaciente1.setEnabled(false);

        lblTipoSangrePaciente1.setText("Tipo de Sangre:");

        txtTipoSangrePaciente1.setEnabled(false);

        lblAlergiasPaciente1.setText("Alergias:");

        txtAlergiasPaciente1.setEnabled(false);

        lblVacunasPaciente1.setText("Vacunas:");

        txtVacunasPaciente1.setEnabled(false);

        lblPrioritarioPaciente1.setText("Prioritario:");

        lblPrioritarioSiNoPaciente1.setText("-");

        btnEditarDatosPaciente1.setText("Editar datos del paciente");
        btnEditarDatosPaciente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarDatosPaciente1ActionPerformed(evt);
            }
        });

        btnCambiarVistaPaciente1.setText("Cambiar de vista");
        btnCambiarVistaPaciente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarVistaPaciente1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabPaciente1Layout = new javax.swing.GroupLayout(tabPaciente1);
        tabPaciente1.setLayout(tabPaciente1Layout);
        tabPaciente1Layout.setHorizontalGroup(
            tabPaciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPaciente1Layout.createSequentialGroup()
                .addGroup(tabPaciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabPaciente1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(tabPaciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblVacunasPaciente1)
                            .addComponent(lblAlergiasPaciente1)
                            .addComponent(lblTipoSangrePaciente1)
                            .addComponent(lblResidenciaPaciente1)
                            .addComponent(lblNacionalidadPaciente1)
                            .addComponent(lblSexoPaciente1)
                            .addComponent(lblApellidosPaciente1)
                            .addComponent(lblNombrePaciente1)
                            .addComponent(lblEdadPaciente1)
                            .addComponent(lblEmailPaciente1)
                            .addComponent(lblTelefonoPaciente1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabPaciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabPaciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNombrePaciente1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(txtApellidosPaciente1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(txtEdadPaciente1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(txtEmailPaciente1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(txtTelefonoPaciente1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                            .addGroup(tabPaciente1Layout.createSequentialGroup()
                                .addComponent(rbHombrePaciente1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbMujerPaciente1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbOtroPaciente1))
                            .addGroup(tabPaciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtResidenciaPaciente1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(txtNacionalidadPaciente1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(txtTipoSangrePaciente1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(txtAlergiasPaciente1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(txtVacunasPaciente1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))))
                    .addGroup(tabPaciente1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblPrioritarioPaciente1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPrioritarioSiNoPaciente1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabPaciente1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(tabPaciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabPaciente1Layout.createSequentialGroup()
                        .addComponent(btnCambiarVistaPaciente1)
                        .addGap(141, 141, 141))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabPaciente1Layout.createSequentialGroup()
                        .addComponent(btnEditarDatosPaciente1)
                        .addGap(120, 120, 120))))
        );
        tabPaciente1Layout.setVerticalGroup(
            tabPaciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPaciente1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(tabPaciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombrePaciente1)
                    .addComponent(txtNombrePaciente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabPaciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidosPaciente1)
                    .addComponent(txtApellidosPaciente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabPaciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEdadPaciente1)
                    .addComponent(txtEdadPaciente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabPaciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmailPaciente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmailPaciente1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabPaciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefonoPaciente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefonoPaciente1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabPaciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSexoPaciente1)
                    .addComponent(rbHombrePaciente1)
                    .addComponent(rbMujerPaciente1)
                    .addComponent(rbOtroPaciente1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabPaciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNacionalidadPaciente1)
                    .addComponent(txtNacionalidadPaciente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabPaciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtResidenciaPaciente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblResidenciaPaciente1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabPaciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoSangrePaciente1)
                    .addComponent(txtTipoSangrePaciente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabPaciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAlergiasPaciente1)
                    .addComponent(txtAlergiasPaciente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabPaciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVacunasPaciente1)
                    .addComponent(txtVacunasPaciente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabPaciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrioritarioPaciente1)
                    .addComponent(lblPrioritarioSiNoPaciente1))
                .addGap(18, 18, 18)
                .addComponent(btnEditarDatosPaciente1)
                .addGap(18, 18, 18)
                .addComponent(btnCambiarVistaPaciente1)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        tbpnPacientes.addTab("Jorge", tabPaciente1);

        tabPaciente2.setPreferredSize(new java.awt.Dimension(400, 550));

        lblNombrePaciente2.setText("Nombre:");

        txtNombrePaciente2.setEnabled(false);

        lblApellidosPaciente2.setText("Apellidos:");

        txtApellidosPaciente2.setEnabled(false);

        lblEdadPaciente2.setText("Edad:");

        txtEdadPaciente2.setEnabled(false);

        lblEmailPaciente2.setText("Email:");

        txtEmailPaciente2.setEnabled(false);

        lblTelefonoPaciente2.setText("Telefono:");

        txtTelefonoPaciente2.setEnabled(false);

        lblSexoPaciente2.setText("Sexo:");

        grupoSexoPaciente2.add(rbHombrePaciente2);
        rbHombrePaciente2.setText("Hombre");
        rbHombrePaciente2.setEnabled(false);

        grupoSexoPaciente2.add(rbMujerPaciente2);
        rbMujerPaciente2.setText("Mujer");
        rbMujerPaciente2.setEnabled(false);

        grupoSexoPaciente2.add(rbOtroPaciente2);
        rbOtroPaciente2.setText("Otro");
        rbOtroPaciente2.setEnabled(false);

        lblNacionalidadPaciente2.setText("Nacionalidad:");

        txtNacionalidadPaciente2.setEnabled(false);

        lblResidenciaPaciente2.setText("Residencia:");

        txtResidenciaPaciente2.setEnabled(false);

        lblTipoSangrePaciente2.setText("Tipo de Sangre:");

        txtTipoSangrePaciente2.setEnabled(false);

        lblAlergiasPaciente2.setText("Alergias:");

        txtAlergiasPaciente2.setEnabled(false);

        lblVacunasPaciente2.setText("Vacunas:");

        txtVacunasPaciente2.setEnabled(false);

        lblPrioritarioPaciente2.setText("Prioritario:");

        lblPrioritarioSiNoPaciente2.setText("-");

        btnEditarDatosPaciente2.setText("Editar datos del paciente");
        btnEditarDatosPaciente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarDatosPaciente2ActionPerformed(evt);
            }
        });

        btnCambiarVistaPaciente2.setText("Cambiar de vista");
        btnCambiarVistaPaciente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarVistaPaciente2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabPaciente2Layout = new javax.swing.GroupLayout(tabPaciente2);
        tabPaciente2.setLayout(tabPaciente2Layout);
        tabPaciente2Layout.setHorizontalGroup(
            tabPaciente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPaciente2Layout.createSequentialGroup()
                .addGroup(tabPaciente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabPaciente2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(tabPaciente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblVacunasPaciente2)
                            .addComponent(lblAlergiasPaciente2)
                            .addComponent(lblTipoSangrePaciente2)
                            .addComponent(lblResidenciaPaciente2)
                            .addComponent(lblNacionalidadPaciente2)
                            .addComponent(lblSexoPaciente2)
                            .addComponent(lblApellidosPaciente2)
                            .addComponent(lblNombrePaciente2)
                            .addComponent(lblEdadPaciente2)
                            .addComponent(lblEmailPaciente2)
                            .addComponent(lblTelefonoPaciente2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabPaciente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabPaciente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNombrePaciente2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(txtApellidosPaciente2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(txtEdadPaciente2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(txtEmailPaciente2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(txtTelefonoPaciente2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                            .addGroup(tabPaciente2Layout.createSequentialGroup()
                                .addComponent(rbHombrePaciente2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbMujerPaciente2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbOtroPaciente2))
                            .addGroup(tabPaciente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtResidenciaPaciente2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(txtNacionalidadPaciente2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(txtTipoSangrePaciente2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(txtAlergiasPaciente2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(txtVacunasPaciente2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))))
                    .addGroup(tabPaciente2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblPrioritarioPaciente2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPrioritarioSiNoPaciente2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabPaciente2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(tabPaciente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabPaciente2Layout.createSequentialGroup()
                        .addComponent(btnEditarDatosPaciente2)
                        .addGap(120, 120, 120))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabPaciente2Layout.createSequentialGroup()
                        .addComponent(btnCambiarVistaPaciente2)
                        .addGap(141, 141, 141))))
        );
        tabPaciente2Layout.setVerticalGroup(
            tabPaciente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPaciente2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(tabPaciente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombrePaciente2)
                    .addComponent(txtNombrePaciente2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabPaciente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidosPaciente2)
                    .addComponent(txtApellidosPaciente2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabPaciente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEdadPaciente2)
                    .addComponent(txtEdadPaciente2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabPaciente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmailPaciente2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmailPaciente2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabPaciente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefonoPaciente2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefonoPaciente2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabPaciente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSexoPaciente2)
                    .addComponent(rbHombrePaciente2)
                    .addComponent(rbMujerPaciente2)
                    .addComponent(rbOtroPaciente2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabPaciente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNacionalidadPaciente2)
                    .addComponent(txtNacionalidadPaciente2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabPaciente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtResidenciaPaciente2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblResidenciaPaciente2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabPaciente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoSangrePaciente2)
                    .addComponent(txtTipoSangrePaciente2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabPaciente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAlergiasPaciente2)
                    .addComponent(txtAlergiasPaciente2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabPaciente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVacunasPaciente2)
                    .addComponent(txtVacunasPaciente2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabPaciente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPrioritarioPaciente2)
                    .addComponent(lblPrioritarioSiNoPaciente2))
                .addGap(18, 18, 18)
                .addComponent(btnEditarDatosPaciente2)
                .addGap(18, 18, 18)
                .addComponent(btnCambiarVistaPaciente2)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        tbpnPacientes.addTab("Pedro", tabPaciente2);

        tabPaciente3.setPreferredSize(new java.awt.Dimension(400, 550));

        lblNombrePaciente3.setText("Nombre:");

        txtNombrePaciente3.setEnabled(false);

        lblApellidosPaciente3.setText("Apellidos:");

        txtApellidosPaciente3.setEnabled(false);

        lblEdadPaciente3.setText("Edad:");

        txtEdadPaciente3.setEnabled(false);
        txtEdadPaciente3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadPaciente3ActionPerformed(evt);
            }
        });

        lblEmailPaciente3.setText("Email:");

        txtEmailPaciente3.setEnabled(false);
        txtEmailPaciente3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailPaciente3ActionPerformed(evt);
            }
        });

        lblTelefonoPaciente3.setText("Telefono:");

        txtTelefonoPaciente3.setEnabled(false);

        lblSexoPaciente3.setText("Sexo:");

        grupoSexoPaciente3.add(rbHombrePaciente3);
        rbHombrePaciente3.setText("Hombre");
        rbHombrePaciente3.setEnabled(false);

        grupoSexoPaciente3.add(rbMujerPaciente3);
        rbMujerPaciente3.setText("Mujer");
        rbMujerPaciente3.setEnabled(false);

        grupoSexoPaciente3.add(rbOtroPaciente3);
        rbOtroPaciente3.setText("Otro");
        rbOtroPaciente3.setEnabled(false);

        lblNacionalidadPaciente3.setText("Nacionalidad:");

        txtNacionalidadPaciente3.setEnabled(false);

        lblResidenciaPaciente3.setText("Residencia:");

        txtResidenciaPaciente3.setEnabled(false);

        lblTipoSangrePaciente3.setText("Tipo de Sangre:");

        txtTipoSangrePaciente3.setEnabled(false);

        lblAlergiasPaciente3.setText("Alergias:");

        txtAlergiasPaciente3.setEnabled(false);

        lblVacunasPaciente3.setText("Vacunas:");

        txtVacunasPaciente3.setEnabled(false);

        lblPrioritarioSiNoPaciente3.setText("-");

        lblPrioritarioPaciente3.setText("Prioritario:");

        btnEditarDatosPaciente3.setText("Editar datos del paciente");
        btnEditarDatosPaciente3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarDatosPaciente3ActionPerformed(evt);
            }
        });

        btnCambiarVistaPaciente3.setText("Cambiar de vista");
        btnCambiarVistaPaciente3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarVistaPaciente3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabPaciente3Layout = new javax.swing.GroupLayout(tabPaciente3);
        tabPaciente3.setLayout(tabPaciente3Layout);
        tabPaciente3Layout.setHorizontalGroup(
            tabPaciente3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPaciente3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(tabPaciente3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAlergiasPaciente3)
                    .addComponent(lblTipoSangrePaciente3)
                    .addComponent(lblResidenciaPaciente3)
                    .addComponent(lblNacionalidadPaciente3)
                    .addComponent(lblSexoPaciente3)
                    .addComponent(lblApellidosPaciente3)
                    .addComponent(lblNombrePaciente3)
                    .addComponent(lblEdadPaciente3)
                    .addComponent(lblEmailPaciente3)
                    .addComponent(lblTelefonoPaciente3)
                    .addComponent(lblVacunasPaciente3)
                    .addComponent(lblPrioritarioPaciente3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabPaciente3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabPaciente3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtNombrePaciente3, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(txtApellidosPaciente3, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(txtEdadPaciente3, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(txtEmailPaciente3, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(txtTelefonoPaciente3, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                    .addGroup(tabPaciente3Layout.createSequentialGroup()
                        .addComponent(rbHombrePaciente3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbMujerPaciente3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbOtroPaciente3))
                    .addComponent(lblPrioritarioSiNoPaciente3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTipoSangrePaciente3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tabPaciente3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtResidenciaPaciente3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(txtNacionalidadPaciente3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(txtAlergiasPaciente3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(txtVacunasPaciente3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabPaciente3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(tabPaciente3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabPaciente3Layout.createSequentialGroup()
                        .addComponent(btnCambiarVistaPaciente3)
                        .addGap(141, 141, 141))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabPaciente3Layout.createSequentialGroup()
                        .addComponent(btnEditarDatosPaciente3)
                        .addGap(120, 120, 120))))
        );
        tabPaciente3Layout.setVerticalGroup(
            tabPaciente3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPaciente3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(tabPaciente3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombrePaciente3)
                    .addComponent(txtNombrePaciente3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabPaciente3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidosPaciente3)
                    .addComponent(txtApellidosPaciente3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabPaciente3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEdadPaciente3)
                    .addComponent(txtEdadPaciente3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabPaciente3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmailPaciente3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmailPaciente3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabPaciente3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefonoPaciente3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefonoPaciente3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabPaciente3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSexoPaciente3)
                    .addComponent(rbHombrePaciente3)
                    .addComponent(rbMujerPaciente3)
                    .addComponent(rbOtroPaciente3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabPaciente3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNacionalidadPaciente3)
                    .addComponent(txtNacionalidadPaciente3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabPaciente3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtResidenciaPaciente3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblResidenciaPaciente3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabPaciente3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoSangrePaciente3)
                    .addComponent(txtTipoSangrePaciente3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabPaciente3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAlergiasPaciente3)
                    .addComponent(txtAlergiasPaciente3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabPaciente3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVacunasPaciente3)
                    .addComponent(txtVacunasPaciente3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabPaciente3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrioritarioPaciente3)
                    .addComponent(lblPrioritarioSiNoPaciente3))
                .addGap(18, 18, 18)
                .addComponent(btnEditarDatosPaciente3)
                .addGap(18, 18, 18)
                .addComponent(btnCambiarVistaPaciente3)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        tbpnPacientes.addTab("Alma", tabPaciente3);

        tabPaciente4.setPreferredSize(new java.awt.Dimension(400, 550));

        lblNombrePaciente4.setText("Nombre:");

        txtNombrePaciente4.setEnabled(false);

        lblApellidosPaciente4.setText("Apellidos:");

        txtApellidosPaciente4.setEnabled(false);

        lblEdadPaciente4.setText("Edad:");

        txtEdadPaciente4.setEnabled(false);

        lblEmailPaciente4.setText("Email:");

        txtEmailPaciente4.setEnabled(false);

        lblTelefonoPaciente4.setText("Telefono:");

        txtTelefonoPaciente4.setEnabled(false);

        lblSexoPaciente4.setText("Sexo:");

        grupoSexoPaciente4.add(rbHombrePaciente4);
        rbHombrePaciente4.setText("Hombre");
        rbHombrePaciente4.setEnabled(false);

        grupoSexoPaciente4.add(rbMujerPaciente4);
        rbMujerPaciente4.setText("Mujer");
        rbMujerPaciente4.setEnabled(false);

        grupoSexoPaciente4.add(rbOtroPaciente4);
        rbOtroPaciente4.setText("Otro");
        rbOtroPaciente4.setEnabled(false);

        lblNacionalidadPaciente4.setText("Nacionalidad:");

        txtNacionalidadPaciente4.setEnabled(false);

        lblResidenciaPaciente4.setText("Residencia:");

        txtResidenciaPaciente4.setEnabled(false);

        lblTipoSangrePaciente4.setText("Tipo de Sangre:");

        txtTipoSangrePaciente4.setEnabled(false);

        lblAlergiasPaciente4.setText("Alergias:");

        txtAlergiasPaciente4.setEnabled(false);

        lblVacunasPaciente4.setText("Vacunas:");

        txtVacunasPaciente4.setEnabled(false);

        lblPrioritarioPaciente4.setText("Prioritario:");

        lblPrioritarioSiNoPaciente4.setText("-");

        btnEditarDatosPaciente4.setText("Editar datos del paciente");
        btnEditarDatosPaciente4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarDatosPaciente4ActionPerformed(evt);
            }
        });

        btnCambiarVistaPaciente4.setText("Cambiar de vista");
        btnCambiarVistaPaciente4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarVistaPaciente4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabPaciente4Layout = new javax.swing.GroupLayout(tabPaciente4);
        tabPaciente4.setLayout(tabPaciente4Layout);
        tabPaciente4Layout.setHorizontalGroup(
            tabPaciente4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPaciente4Layout.createSequentialGroup()
                .addGroup(tabPaciente4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabPaciente4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(tabPaciente4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblVacunasPaciente4)
                            .addComponent(lblAlergiasPaciente4)
                            .addComponent(lblTipoSangrePaciente4)
                            .addComponent(lblResidenciaPaciente4)
                            .addComponent(lblNacionalidadPaciente4)
                            .addComponent(lblSexoPaciente4)
                            .addComponent(lblApellidosPaciente4)
                            .addComponent(lblNombrePaciente4)
                            .addComponent(lblEdadPaciente4)
                            .addComponent(lblEmailPaciente4)
                            .addComponent(lblTelefonoPaciente4)
                            .addComponent(lblPrioritarioPaciente4))
                        .addGroup(tabPaciente4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabPaciente4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(tabPaciente4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombrePaciente4, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(txtApellidosPaciente4, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(txtEdadPaciente4, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(txtEmailPaciente4, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(txtTelefonoPaciente4, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                            .addGroup(tabPaciente4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNacionalidadPaciente4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tabPaciente4Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(tabPaciente4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPrioritarioSiNoPaciente4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(tabPaciente4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtResidenciaPaciente4, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtTipoSangrePaciente4, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtAlergiasPaciente4, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtVacunasPaciente4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(tabPaciente4Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(rbHombrePaciente4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbMujerPaciente4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbOtroPaciente4)))
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabPaciente4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(tabPaciente4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabPaciente4Layout.createSequentialGroup()
                        .addComponent(btnEditarDatosPaciente4)
                        .addGap(120, 120, 120))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabPaciente4Layout.createSequentialGroup()
                        .addComponent(btnCambiarVistaPaciente4)
                        .addGap(141, 141, 141))))
        );
        tabPaciente4Layout.setVerticalGroup(
            tabPaciente4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPaciente4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(tabPaciente4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombrePaciente4)
                    .addComponent(txtNombrePaciente4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabPaciente4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidosPaciente4)
                    .addComponent(txtApellidosPaciente4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabPaciente4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEdadPaciente4)
                    .addComponent(txtEdadPaciente4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabPaciente4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmailPaciente4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmailPaciente4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabPaciente4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefonoPaciente4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefonoPaciente4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabPaciente4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSexoPaciente4)
                    .addComponent(rbHombrePaciente4)
                    .addComponent(rbMujerPaciente4)
                    .addComponent(rbOtroPaciente4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabPaciente4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNacionalidadPaciente4)
                    .addComponent(txtNacionalidadPaciente4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabPaciente4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblResidenciaPaciente4)
                    .addComponent(txtResidenciaPaciente4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabPaciente4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTipoSangrePaciente4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipoSangrePaciente4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabPaciente4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAlergiasPaciente4)
                    .addComponent(txtAlergiasPaciente4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabPaciente4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVacunasPaciente4)
                    .addComponent(txtVacunasPaciente4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(tabPaciente4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrioritarioPaciente4)
                    .addComponent(lblPrioritarioSiNoPaciente4))
                .addGap(18, 18, 18)
                .addComponent(btnEditarDatosPaciente4)
                .addGap(18, 18, 18)
                .addComponent(btnCambiarVistaPaciente4)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        tbpnPacientes.addTab("Luis", tabPaciente4);

        getContentPane().add(tbpnPacientes, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEdadPaciente3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadPaciente3ActionPerformed
    }//GEN-LAST:event_txtEdadPaciente3ActionPerformed

    private void txtEmailPaciente3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailPaciente3ActionPerformed
    }//GEN-LAST:event_txtEmailPaciente3ActionPerformed

    private void btnEditarDatosPaciente4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarDatosPaciente4ActionPerformed
        mostrarEditarDatos();
        ventEditarDatos.setDatos(Luis);
        ventEditarDatos.ventAnterior = "Ventana Pacientes";
    }//GEN-LAST:event_btnEditarDatosPaciente4ActionPerformed

    private void btnEditarDatosPaciente3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarDatosPaciente3ActionPerformed
        mostrarEditarDatos();
        ventEditarDatos.setDatos(Alma);
        ventEditarDatos.ventAnterior = "Ventana Pacientes";
    }//GEN-LAST:event_btnEditarDatosPaciente3ActionPerformed

    private void btnEditarDatosPaciente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarDatosPaciente2ActionPerformed
        mostrarEditarDatos();
        ventEditarDatos.setDatos(Pedro);
        ventEditarDatos.ventAnterior = "Ventana Pacientes";
    }//GEN-LAST:event_btnEditarDatosPaciente2ActionPerformed

    private void tbpnPacientesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tbpnPacientesStateChanged
        System.out.println("Pestaña cambiada.");
    }//GEN-LAST:event_tbpnPacientesStateChanged

    private void btnEditarDatosPaciente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarDatosPaciente1ActionPerformed
        mostrarEditarDatos();
        ventEditarDatos.setDatos(Jorge);
        ventEditarDatos.ventAnterior = "Ventana Pacientes";
    }//GEN-LAST:event_btnEditarDatosPaciente1ActionPerformed

    private void btnCambiarVistaPaciente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarVistaPaciente1ActionPerformed
        mostrarListaPacientes();
        ventListaPacientes.LlenadoDeDatos(Jorge);
    }//GEN-LAST:event_btnCambiarVistaPaciente1ActionPerformed

    private void btnCambiarVistaPaciente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarVistaPaciente2ActionPerformed
        mostrarListaPacientes();
        ventListaPacientes.LlenadoDeDatos(Pedro);
    }//GEN-LAST:event_btnCambiarVistaPaciente2ActionPerformed

    private void btnCambiarVistaPaciente3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarVistaPaciente3ActionPerformed
        mostrarListaPacientes();
        ventListaPacientes.LlenadoDeDatos(Alma);
    }//GEN-LAST:event_btnCambiarVistaPaciente3ActionPerformed

    private void btnCambiarVistaPaciente4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarVistaPaciente4ActionPerformed
        mostrarListaPacientes();
        ventListaPacientes.LlenadoDeDatos(Luis);
    }//GEN-LAST:event_btnCambiarVistaPaciente4ActionPerformed

    public void LlenadoDeDatos(){
            txtNombrePaciente1.setText(Jorge.getNombre());              //Paciente 1
            txtApellidosPaciente1.setText(Jorge.getApellidos());
            txtEdadPaciente1.setText("" + Jorge.getEdad());
            txtEmailPaciente1.setText(Jorge.getEmail());
            txtTelefonoPaciente1.setText(Jorge.getTelefono());
            rbHombrePaciente1.setSelected(true);
            txtNacionalidadPaciente1.setText(Jorge.getNacionalidad());
            txtResidenciaPaciente1.setText(Jorge.getResidencia());
            txtTipoSangrePaciente1.setText(Jorge.getTipoSangre());
            txtAlergiasPaciente1.setText(Jorge.getAlergias());
            txtVacunasPaciente1.setText(Jorge.getVacunas());
            lblPrioritarioSiNoPaciente1.setText("Si");
            txtNombrePaciente2.setText(Pedro.getNombre());              //Paciente 2
            txtApellidosPaciente2.setText(Pedro.getApellidos());
            txtEdadPaciente2.setText("" + Pedro.getEdad());
            txtEmailPaciente2.setText(Pedro.getEmail());
            txtTelefonoPaciente2.setText(Pedro.getTelefono());
            rbOtroPaciente2.setSelected(true);
            txtNacionalidadPaciente2.setText(Pedro.getNacionalidad());
            txtResidenciaPaciente2.setText(Pedro.getResidencia());
            txtTipoSangrePaciente2.setText(Pedro.getTipoSangre());
            txtAlergiasPaciente2.setText(Pedro.getAlergias());
            txtVacunasPaciente2.setText(Pedro.getVacunas());
            lblPrioritarioSiNoPaciente2.setText("Si");
            txtNombrePaciente3.setText(Alma.getNombre());              //Paciente 3
            txtApellidosPaciente3.setText(Alma.getApellidos());
            txtEdadPaciente3.setText("" + Alma.getEdad());
            txtEmailPaciente3.setText(Alma.getEmail());
            txtTelefonoPaciente3.setText(Alma.getTelefono());
            rbMujerPaciente3.setSelected(true);
            txtNacionalidadPaciente3.setText(Alma.getNacionalidad());
            txtResidenciaPaciente3.setText(Alma.getResidencia());
            txtTipoSangrePaciente3.setText(Alma.getTipoSangre());
            txtAlergiasPaciente3.setText(Alma.getAlergias());
            txtVacunasPaciente3.setText(Alma.getVacunas());
            lblPrioritarioSiNoPaciente3.setText("No");
            txtNombrePaciente4.setText(Luis.getNombre());              //Paciente 4
            txtApellidosPaciente4.setText(Luis.getApellidos());
            txtEdadPaciente4.setText("" + Luis.getEdad());
            txtEmailPaciente4.setText(Luis.getEmail());
            txtTelefonoPaciente4.setText(Luis.getTelefono());
            rbHombrePaciente4.setSelected(true);
            txtNacionalidadPaciente4.setText(Luis.getNacionalidad());
            txtResidenciaPaciente4.setText(Luis.getResidencia());
            txtTipoSangrePaciente4.setText(Luis.getTipoSangre());
            txtAlergiasPaciente4.setText(Luis.getAlergias());
            txtVacunasPaciente4.setText(Luis.getVacunas());
            lblPrioritarioSiNoPaciente4.setText("No");
    }

    public void mostrarEditarDatos(){
        if(ventEditarDatos == null){
            ventEditarDatos = new EditarDatos(this, ventListaPacientes, Jorge, Pedro, Alma, Luis);
        }
        this.setVisible(false);
        ventEditarDatos.setVisible(true);
    }

    public void mostrarListaPacientes(){
        if(ventListaPacientes == null){
            ventListaPacientes = new VentanaListaPacientes(this, ventEditarDatos, Jorge, Pedro, Alma, Luis);
        }
        this.setVisible(false);
        ventListaPacientes.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPacientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiarVistaPaciente1;
    private javax.swing.JButton btnCambiarVistaPaciente2;
    private javax.swing.JButton btnCambiarVistaPaciente3;
    private javax.swing.JButton btnCambiarVistaPaciente4;
    private javax.swing.JButton btnEditarDatosPaciente1;
    private javax.swing.JButton btnEditarDatosPaciente2;
    private javax.swing.JButton btnEditarDatosPaciente3;
    private javax.swing.JButton btnEditarDatosPaciente4;
    private javax.swing.ButtonGroup grupoSexoPaciente1;
    private javax.swing.ButtonGroup grupoSexoPaciente2;
    private javax.swing.ButtonGroup grupoSexoPaciente3;
    private javax.swing.ButtonGroup grupoSexoPaciente4;
    private javax.swing.JLabel lblAlergiasPaciente1;
    private javax.swing.JLabel lblAlergiasPaciente2;
    private javax.swing.JLabel lblAlergiasPaciente3;
    private javax.swing.JLabel lblAlergiasPaciente4;
    private javax.swing.JLabel lblApellidosPaciente1;
    private javax.swing.JLabel lblApellidosPaciente2;
    private javax.swing.JLabel lblApellidosPaciente3;
    private javax.swing.JLabel lblApellidosPaciente4;
    private javax.swing.JLabel lblEdadPaciente1;
    private javax.swing.JLabel lblEdadPaciente2;
    private javax.swing.JLabel lblEdadPaciente3;
    private javax.swing.JLabel lblEdadPaciente4;
    private javax.swing.JLabel lblEmailPaciente1;
    private javax.swing.JLabel lblEmailPaciente2;
    private javax.swing.JLabel lblEmailPaciente3;
    private javax.swing.JLabel lblEmailPaciente4;
    private javax.swing.JLabel lblNacionalidadPaciente1;
    private javax.swing.JLabel lblNacionalidadPaciente2;
    private javax.swing.JLabel lblNacionalidadPaciente3;
    private javax.swing.JLabel lblNacionalidadPaciente4;
    private javax.swing.JLabel lblNombrePaciente1;
    private javax.swing.JLabel lblNombrePaciente2;
    private javax.swing.JLabel lblNombrePaciente3;
    private javax.swing.JLabel lblNombrePaciente4;
    private javax.swing.JLabel lblPrioritarioPaciente1;
    private javax.swing.JLabel lblPrioritarioPaciente2;
    private javax.swing.JLabel lblPrioritarioPaciente3;
    private javax.swing.JLabel lblPrioritarioPaciente4;
    private javax.swing.JLabel lblPrioritarioSiNoPaciente1;
    private javax.swing.JLabel lblPrioritarioSiNoPaciente2;
    private javax.swing.JLabel lblPrioritarioSiNoPaciente3;
    private javax.swing.JLabel lblPrioritarioSiNoPaciente4;
    private javax.swing.JLabel lblResidenciaPaciente1;
    private javax.swing.JLabel lblResidenciaPaciente2;
    private javax.swing.JLabel lblResidenciaPaciente3;
    private javax.swing.JLabel lblResidenciaPaciente4;
    private javax.swing.JLabel lblSexoPaciente1;
    private javax.swing.JLabel lblSexoPaciente2;
    private javax.swing.JLabel lblSexoPaciente3;
    private javax.swing.JLabel lblSexoPaciente4;
    private javax.swing.JLabel lblTelefonoPaciente1;
    private javax.swing.JLabel lblTelefonoPaciente2;
    private javax.swing.JLabel lblTelefonoPaciente3;
    private javax.swing.JLabel lblTelefonoPaciente4;
    private javax.swing.JLabel lblTipoSangrePaciente1;
    private javax.swing.JLabel lblTipoSangrePaciente2;
    private javax.swing.JLabel lblTipoSangrePaciente3;
    private javax.swing.JLabel lblTipoSangrePaciente4;
    private javax.swing.JLabel lblVacunasPaciente1;
    private javax.swing.JLabel lblVacunasPaciente2;
    private javax.swing.JLabel lblVacunasPaciente3;
    private javax.swing.JLabel lblVacunasPaciente4;
    private javax.swing.JRadioButton rbHombrePaciente1;
    private javax.swing.JRadioButton rbHombrePaciente2;
    private javax.swing.JRadioButton rbHombrePaciente3;
    private javax.swing.JRadioButton rbHombrePaciente4;
    private javax.swing.JRadioButton rbMujerPaciente1;
    private javax.swing.JRadioButton rbMujerPaciente2;
    private javax.swing.JRadioButton rbMujerPaciente3;
    private javax.swing.JRadioButton rbMujerPaciente4;
    private javax.swing.JRadioButton rbOtroPaciente1;
    private javax.swing.JRadioButton rbOtroPaciente2;
    private javax.swing.JRadioButton rbOtroPaciente3;
    private javax.swing.JRadioButton rbOtroPaciente4;
    private javax.swing.JPanel tabPaciente1;
    private javax.swing.JPanel tabPaciente2;
    private javax.swing.JPanel tabPaciente3;
    private javax.swing.JPanel tabPaciente4;
    private javax.swing.JTabbedPane tbpnPacientes;
    private javax.swing.JTextField txtAlergiasPaciente1;
    private javax.swing.JTextField txtAlergiasPaciente2;
    private javax.swing.JTextField txtAlergiasPaciente3;
    private javax.swing.JTextField txtAlergiasPaciente4;
    private javax.swing.JTextField txtApellidosPaciente1;
    private javax.swing.JTextField txtApellidosPaciente2;
    private javax.swing.JTextField txtApellidosPaciente3;
    private javax.swing.JTextField txtApellidosPaciente4;
    private javax.swing.JTextField txtEdadPaciente1;
    private javax.swing.JTextField txtEdadPaciente2;
    private javax.swing.JTextField txtEdadPaciente3;
    private javax.swing.JTextField txtEdadPaciente4;
    private javax.swing.JTextField txtEmailPaciente1;
    private javax.swing.JTextField txtEmailPaciente2;
    private javax.swing.JTextField txtEmailPaciente3;
    private javax.swing.JTextField txtEmailPaciente4;
    private javax.swing.JTextField txtNacionalidadPaciente1;
    private javax.swing.JTextField txtNacionalidadPaciente2;
    private javax.swing.JTextField txtNacionalidadPaciente3;
    private javax.swing.JTextField txtNacionalidadPaciente4;
    private javax.swing.JTextField txtNombrePaciente1;
    private javax.swing.JTextField txtNombrePaciente2;
    private javax.swing.JTextField txtNombrePaciente3;
    private javax.swing.JTextField txtNombrePaciente4;
    private javax.swing.JTextField txtResidenciaPaciente1;
    private javax.swing.JTextField txtResidenciaPaciente2;
    private javax.swing.JTextField txtResidenciaPaciente3;
    private javax.swing.JTextField txtResidenciaPaciente4;
    private javax.swing.JTextField txtTelefonoPaciente1;
    private javax.swing.JTextField txtTelefonoPaciente2;
    private javax.swing.JTextField txtTelefonoPaciente3;
    private javax.swing.JTextField txtTelefonoPaciente4;
    private javax.swing.JTextField txtTipoSangrePaciente1;
    private javax.swing.JTextField txtTipoSangrePaciente2;
    private javax.swing.JTextField txtTipoSangrePaciente3;
    private javax.swing.JTextField txtTipoSangrePaciente4;
    private javax.swing.JTextField txtVacunasPaciente1;
    private javax.swing.JTextField txtVacunasPaciente2;
    private javax.swing.JTextField txtVacunasPaciente3;
    private javax.swing.JTextField txtVacunasPaciente4;
    // End of variables declaration//GEN-END:variables
}
